### ISSUE TITLE
WordPress Easy Forms for Mailchimp plugin <= 6.8.10 - Sensitive Data Exposure via Log File vulnerability

### ISSUE THREAD

**Issue by hitec4ever** [EvanHerman/yikes-inc-easy-mailchimp-extender#916]
Details

Sensitive Data Exposure via Log File vulnerability discovered by Joshua Chan (Patchstack Alliance) in WordPress Plugin Easy Forms for Mailchimp (versions <= 6.8.10)

https://patchstack.com/database/vulnerability/yikes-inc-easy-mailchimp-extender/wordpress-easy-forms-for-mailchimp-plugin-6-8-10-sensitive-data-exposure-via-log-file-vulnerability?_a_id=431

**Comment by Alongar** [comment]
Also, another vulnerability as well:

https://wpscan.com/vulnerability/0b094cba-9288-4c9c-87a9-bdce286fe8b6/

There are 2 known security issues as of 2/19/24.

**Comment by EvanHerman** [comment]
Thank you both. I am looking into this and will have a fix out ASAP.
